baseURL = 'https://carlosnexans.com/'
sectionPagesMenu = 'main'
theme = "nxtypo"
languageCode = 'es-es'
defaultContentLanguage = "es"
defaultContentLanguageInSubdir = true
[languages]
  [languages.es]
    contentDir = 'content/es'
    disabled = false
    languageCode = 'es-ES'
    languageDirection = 'ltr'
    languageName = 'Español'
    weight = 1
    title = 'Carlos Nexans'
    [languages.es.params]
      # Collection to display on home
      homeCollectionTitle = 'Ultimas publicaciones'
      homeCollection = 'articulos'
      # Main menu pages
      [[languages.es.params.menu]]
      name = "Home"
      url = "/"
      [[languages.es.params.menu]]
      name = "Blog"
      url = "/es/articulos"
      [[languages.es.params.menu]]
      name = "Tutoriales"
      url = "/es/tutoriales"
  [languages.en]
    contentDir = 'content/en'
    disabled = false
    languageCode = 'en-US'
    languageDirection = 'ltr'
    languageName = 'English'
    weight = 2
    title = 'Carlos Nexans'
    [languages.en.params]
      # Collection to display on home
      homeCollectionTitle = 'Latests articles'
      homeCollection = 'articles'
      # Main menu pages
      [[languages.en.params.menu]]
      name = "Home"
      url = "/en"
      [[languages.en.params.menu]]
      name = "Blog"
      url = "/en/articles"
      [[languages.en.params.menu]]
      name = "Tutorials"
      url = "/en/tutorials"

[taxonomies]
tag = 'tags'

# Google analytics code
[params]
defaultTheme = "light"
googleAnalytics = "G-27XYP663Z6"

# posthog
posthog = "phc_V86sv23tZmpoIKoMxp8E9nd3w3BxMM5vw5GYtZlOXrY"
posthogEnabled = true

# Meta description
description = "Website y blog de tecnología de Carlos Nexans"
avatar = "/brand/logo.png"
author = "Carlos Nexans"

# Appearance settings
theme = 'auto'
colorPalette = 'default'
hideHeader = false

# Intro on main page, content is markdown
# homeIntroTitle = 'Hi!'
#homeIntroContent = """
#I am an Italian Software Engineer with a strong foundation in computer science and a passion for solving complex problems.
#I am interested in a range of topics, including algorithms, distributed systems, databases, and information retrieval.
#"""

# Lists parameters
paginationSize = 10
listSummaries = false
listDateFormat = '2 Jan 2006'

# Breadcrumbs
breadcrumbs = true
mermaid = true

[params.utteranc]
repo = "cdgn-coding/website"
issueTerm = "pathname"
enable = true

[params.comments]
enable = true

# Social icons
[[params.social]]
name = "linkedin"
url = "https://www.linkedin.com/in/cdgn-cv/"

[[params.social]]
name = "medium"
url = "https://medium.com/@nexanscarlos"

[[params.social]]
name = "github"
url = "https://github.com/cdgn-coding"

[[params.social]]
name = "x"
url = "https://x.com/techycarlos"

# Syntax highligth on code blocks
[markup]
[markup.highlight]
style = 'github-dark'
noClasses = true

[markup.goldmark.renderer]
  unsafe = true # Allow HTML in md files